### ISSUE TITLE
ng2 RC.6: Error: Only selectors matching element names are supported

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/ng1-to-ng2#13]
RC.6 won't import UIRouterLibraryModule into the ngUpgrade bootstrap.
ui-view isn't being downgraded/upgraded, but this error still occurs.

See the ng2 RC.6 issue https://github.com/angular/angular/issues/11280 and the earlier issue explaining the intent of this error message: https://github.com/angular/angular/issues/7026

```js
@UIRouterModule({
  imports: [BrowserModule, Ng1ToNg2Module],
  providers: [
    { provide: NgModuleFactoryLoader, useClass: SystemJsNgModuleLoader }
  ]
}) class SampleAppModule {}

export const upgradeAdapter = new UpgradeAdapter(SampleAppModule);
uiRouterNgUpgrade.setUpgradeAdapter(upgradeAdapter);
upgradeAdapter.bootstrap(document.body, ['demo']);
```

```
Error: Only selectors matching element names are supported, got: ui-view, [ui-view](…) "Error: Only selectors matching element names are supported, got: ui-view, [ui-view]
    at getComponentInfo (http://localhost:8000/node_modules/@angular/upgrade/bundles/upgrade.umd.js:234:19)
    at eval (http://localhost:8000/node_modules/@angular/upgrade/bundles/upgrade.umd.js:962:60)
    at Array.forEach (native)
    at eval (http://localhost:8000/node_modules/@angular/upgrade/bundles/upgrade.umd.js:961:52)
    at eval (http://localhost:8000/node_modules/@angular/core/bundles/core.umd.js:9484:21)
    at ZoneDelegate.invoke (http://localhost:8000/node_modules/zone.js/dist/zone.js:332:29)
    at Object.onInvoke (http://localhost:8000/node_modules/@angular/core/bundles/core.umd.js:8772:45)
    at ZoneDelegate.invoke (http://localhost:8000/node_modules/zone.js/dist/zone.js:331:35)
    at Zone.run (http://localhost:8000/node_modules/zone.js/dist/zone.js:225:44)
    at http://localhost:8000/node_modules/zone.js/dist/zone.js:591:58"
```

**Comment by christopherthielen** [comment]
Fixed by 2e6c4f7fa54bb27ca10d95ad028456a00dee820b
